# Generated by Django 3.0.3 on 2020-04-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200408_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('front_width', models.CharField(max_length=100)),
                ('back_width', models.CharField(max_length=100)),
                ('depth', models.CharField(max_length=100)),
                ('chest', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_id', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('dad_id', models.CharField(max_length=100)),
                ('mom_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='data',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this pig', to='catalog.Genre'),
        ),
        migrations.AddField(
            model_name='data',
            name='pig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Pig'),
        ),
    ]
