# Generated by Django 3.0.3 on 2020-04-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200409_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='genre',
        ),
        migrations.AlterField(
            model_name='pig',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this pig', to='catalog.Genre'),
        ),
    ]
