# Generated by Django 3.0.5 on 2020-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200409_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='pig',
            name='id',
        ),
        migrations.AddField(
            model_name='data',
            name='back_cannon_circumference',
            field=models.FloatField(help_text='Input front cannon circumference in cm.', null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='data_id',
            field=models.CharField(help_text='Input date + pig_id', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='front_cannon_circumference',
            field=models.FloatField(help_text='Input front cannon circumference in cm.', null=True),
        ),
        migrations.AddField(
            model_name='pig',
            name='breed',
            field=models.CharField(blank=True, choices=[('L', 'Landrace'), ('Y', 'Yorkshire'), ('D', 'Duroc')], help_text="Pig's breed", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='back_width',
            field=models.FloatField(help_text='Input back width in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='chest',
            field=models.FloatField(help_text='Input chest in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(help_text='Input measuring date.', null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='depth',
            field=models.FloatField(help_text='Input body depth in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='front_width',
            field=models.FloatField(help_text='Input front width in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='height',
            field=models.FloatField(help_text='Input height in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='length',
            field=models.FloatField(help_text='Input body length in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='weight',
            field=models.FloatField(help_text='Input weight in kg.'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(help_text='Input birth year(XX) + ear tag', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
