# Generated by Django 3.0.5 on 2020-05-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200414_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='id',
        ),
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.AutoField(default=345, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
