# Generated by Django 3.0.5 on 2020-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_pig_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pig_history',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
