# Generated by Django 3.0.5 on 2020-05-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200521_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_history',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pig_history',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
