# Generated by Django 3.0.3 on 2020-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_pig_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='back_cannon_circumference',
            field=models.FloatField(help_text='Input front cannon circumference in cm.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(help_text='Input measuring date.'),
        ),
        migrations.AlterField(
            model_name='data',
            name='front_cannon_circumference',
            field=models.FloatField(help_text='Input front cannon circumference in cm.'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='breed',
            field=models.CharField(help_text="Pig's breed", max_length=10),
        ),
        migrations.AlterField(
            model_name='pig',
            name='dad_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pig',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pig',
            name='mom_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='camera',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='photographer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
