# Generated by Django 3.0.3 on 2020-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200602_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data_history',
            name='data_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
