# Generated by Django 3.0.3 on 2020-07-06 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200602_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig_video',
            name='video_frame',
            field=models.FileField(null=True, upload_to='video_frame'),
        ),
        migrations.CreateModel(
            name='Pig_Deep_Video',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='pig_deep_video')),
                ('photographer', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('camera', models.CharField(blank=True, max_length=40, null=True)),
                ('pig_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Pig')),
            ],
        ),
    ]
