# Generated by Django 3.0.3 on 2020-07-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200706_1659'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pig_Deep_Video',
            new_name='Pig_Depth_Video',
        ),
    ]
