# Generated by Django 3.0.3 on 2020-07-10 02:44

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20200708_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data_history',
            name='data_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pig',
            name='pig_id',
            field=models.CharField(help_text='Input birth year(XX) + ear tag', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pig_depth_video',
            name='video',
            field=models.FileField(upload_to=catalog.models.pig_directory_path),
        ),
        migrations.AlterField(
            model_name='pig_depth_video',
            name='video_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pig_history',
            name='pig_id',
            field=models.CharField(help_text='Input birth year(XX) + ear tag', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='video',
            field=models.FileField(upload_to=catalog.models.pig_directory_path),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='video_frame',
            field=models.FileField(null=True, upload_to=catalog.models.pig_directory_path),
        ),
        migrations.AlterField(
            model_name='pig_video',
            name='video_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
