# Generated by Django 3.0.3 on 2020-07-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200710_1044'),
        ('catalog', '0024_auto_20200709_1534'),
    ]

    operations = [
    ]
